name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
      - run: go build .
      - run: go test -v -count=1 ./...
